Make our refspec actually take effect.
Using --mirror=push makes the listed refspec obsolete. Undo that and
force push with pruning, so that the target ends up the way we want it
to.

We still need a solution to have unimportant tags show up somewhere
else. Maybe vendor/tags ?

diff --git a/git_conv b/git_conv
--- a/git_conv
+++ b/git_conv
@@ -209,34 +209,38 @@ svn2git()
 	    # to take 1 or 2 extra steps.
 	    case "$TYPE" in
 		base)
-		    git remote add --mirror=push freebsd ssh://git@githome.nyi.freebsd.org/src
-		    git config --add remote.freebsd.push '+refs/heads/*:refs/heads/*'
+		    git remote add freebsd ssh://git@githome.nyi.freebsd.org/src
+		    git config --add remote.freebsd.push '+refs/heads/master:refs/heads/master'
 		    git config --add remote.freebsd.push '+refs/heads/release/*:refs/heads/release/*'
 		    git config --add remote.freebsd.push '+refs/heads/releng/*:refs/heads/releng/*'
 		    git config --add remote.freebsd.push '+refs/heads/stable/*:refs/heads/stable/*'
-		    git config --add remote.freebsd.push '+refs/heads/vendor/*:refs/vendor/*'
-		    git config --add remote.freebsd.push '+refs/heads/vendor-sys/*:refs/vendor-sys/*'
-		    git config --add remote.freebsd.push '+refs/heads/projects/*:refs/projects/*'
-		    git config --add remote.freebsd.push '+refs/heads/user/*:refs/user/*'
-		    git config --add remote.freebsd.push '+refs/heads/cvs2svn/*:refs/cvs2svn/*'
 		    git config --add remote.freebsd.push '+refs/tags/*:refs/tags/*'
 		    git config --add remote.freebsd.push '+refs/notes/*:refs/notes/*'
+
+		    git config --add remote.freebsd.push '+refs/heads/backups/*:refs/backups/*'
+		    git config --add remote.freebsd.push '+refs/heads/cvs2svn/*:refs/cvs2svn/*'
+		    git config --add remote.freebsd.push '+refs/heads/projects/*:refs/projects/*'
+		    git config --add remote.freebsd.push '+refs/heads/user/*:refs/user/*'
+		    git config --add remote.freebsd.push '+refs/heads/vendor-sys/*:refs/vendor-sys/*'
+		    git config --add remote.freebsd.push '+refs/heads/vendor/*:refs/vendor/*'
 		    ;;
 		doc)
-		    git remote add --mirror=push freebsd ssh://git@githome.nyi.freebsd.org/doc
-		    git config --add remote.freebsd.push '+refs/heads/*:refs/heads/*'
+		    git remote add freebsd ssh://git@githome.nyi.freebsd.org/doc
+		    git config --add remote.freebsd.push '+refs/heads/master:refs/heads/master'
+		    git config --add remote.freebsd.push '+refs/tags/*:refs/tags/*'
+		    git config --add remote.freebsd.push '+refs/notes/*:refs/notes/*'
+
 		    git config --add remote.freebsd.push '+refs/heads/projects/*:refs/projects/*'
 		    git config --add remote.freebsd.push '+refs/heads/user/*:refs/user/*'
-		    git config --add remote.freebsd.push '+refs/tags/*:refs/tags/*'
-		    git config --add remote.freebsd.push '+refs/notes/*:refs/notes/*'
 		    ;;
 		ports)
-		    git remote add --mirror=push freebsd ssh://git@githome.nyi.freebsd.org/ports
-		    git config --add remote.freebsd.push '+refs/heads/*:refs/heads/*'
+		    git remote add freebsd ssh://git@githome.nyi.freebsd.org/ports
+		    git config --add remote.freebsd.push '+refs/heads/master:refs/heads/master'
 		    git config --add remote.freebsd.push '+refs/heads/branches/*:refs/heads/branches/*'
-		    git config --add remote.freebsd.push '+refs/heads/projects/*:refs/projects/*'
 		    git config --add remote.freebsd.push '+refs/tags/*:refs/tags/*'
 		    git config --add remote.freebsd.push '+refs/notes/*:refs/notes/*'
+
+		    git config --add remote.freebsd.push '+refs/heads/projects/*:refs/projects/*'
 		    ;;
 	    esac
 	)
@@ -265,7 +269,7 @@ svn2git()
 
     echo "Pushing $target to $dest"
     for d in $dest; do
-	{ cd $target && git push $d; } || { echo "Error in pushing to $dest" >&2; exit 1; }
+	{ cd $target && git push -v --prune -f $d; } || { echo "Error in pushing to $dest" >&2; exit 1; }
     done
 }
 
