git_conv: push to bitbucket and googlecode (again).

diff --git a/git_conv b/git_conv
--- a/git_conv
+++ b/git_conv
@@ -24,8 +24,6 @@
 # - git svn rebase
 # - git push github
 
-LOCK=/tmp/gitconv.lock
-
 : ${BASE=/home/git}
 : ${RULES_DIR=${BASE}}
 : ${SVN2GIT=${BASE}/svn2git/svn-all-fast-export}
@@ -34,6 +32,7 @@ LOCK=/tmp/gitconv.lock
 : ${DOC_REPO=/home/svn/doc}
 : ${PORTS_REPO=/home/svn/ports}
 
+LOCK=/tmp/gitconv.lock
 trap 'rm -f ${LOCK} ; exit 1' 1 2 3 15
 if ! shlock -p $$ -f ${LOCK}; then
     echo "Locked by `cat ${LOCK}`, running too long? Please fix ..." >&2
@@ -69,8 +68,7 @@ svn2git()
 
     echo "Pushing $target to $dest"
     cd $target && for d in $dest; do
-	# XXX freebsd-ports often needs a second try
-	git push $d || git push $d || { echo "Error in pushing to $dest" >&2; exit 1; }
+	git push $d || { echo "Error in pushing to $dest" >&2; exit 1; }
     done
 }
 
@@ -103,6 +101,6 @@ gitsvn src-head.git github
 gitsvn doc-head.git github
 gitsvn ports-head.git github
 
-svn2git $RULES_DIR/freebsd-base.rules ${SRC_REPO} github
+svn2git $RULES_DIR/freebsd-base.rules ${SRC_REPO} github bitbucket googlecode
 svn2git $RULES_DIR/freebsd-doc.rules ${DOC_REPO} github
 svn2git $RULES_DIR/freebsd-ports.rules ${PORTS_REPO} github
