Assorted fixes after rejiggering the run-user on cgit

diff --git a/git_conv_cron b/git_conv_cron
--- a/git_conv_cron
+++ b/git_conv_cron
@@ -6,9 +6,9 @@ TYPE=$1
 REPO=$TYPE
 case $TYPE in base) REPO=src;; esac
 
-LOG="`date +%Y-%m-%d`_${TYPE}.log"
+cd $HOME/git_conv
+LOG="$PWD/`date +%Y-%m-%d`_${TYPE}.log"
 
-cd /home/uqs/git_conv
 (git pull && cd svn2git && make) >> $LOG 2>&1
 
 ./svnmir.sh -1
@@ -43,6 +43,8 @@ if [ $? != 0 ]; then
     tail -30 $LOG
     exit 1
 else
-    # push and leave a marker to indicate a GC run.
-    cd freebsd-$1.git && git push freebsd && echo $REPO >> /home/git/git_gc_semaphore
+    { cd freebsd-$1.git && git push -q freebsd && cd $HOME/repositories/$REPO.git && git gc --aggressive --prune=now --force --quiet } >> $LOG 2>&1
+    echo "Error during git_conv pushing" >&2
+    tail -30 $LOG
+    exit 1
 fi
