Prep for the repo re-roll by using freebsd-base as the new name (which matches the naming scheme better anyway).
This is not yet pushed to github (obviously). Also add a kludge for the ".git"
problem, that we need until we can really re-roll the repo, deterministically.

diff --git a/git_conv b/git_conv
--- a/git_conv
+++ b/git_conv
@@ -63,9 +63,16 @@ svn2git()
 	exit 1
     fi
 
+    if [ -z "$dest" ]; then
+	return
+    fi
+
     echo "Pushing $target to $dest"
     cd $target && for d in $dest; do
-	git push $d || { echo "Error in pushing to $dest" >&2; exit 1; }
+        # XXX kludge around this till we can re-gen the whole thing
+	git update-ref -d refs/heads/user/uqs/git_conv >/dev/null 2>&1
+	# XXX freebsd-ports often needs a second try
+	git push $d || git push $d || { echo "Error in pushing to $dest" >&2; exit 1; }
     done
 }
 
@@ -84,6 +91,10 @@ gitsvn()
 	exit 1
     fi
 
+    if [ -z "$dest" ]; then
+	return
+    fi
+
     echo "Pushing $target to $dest"
     for d in $dest; do
 	git push $d || { echo "Error in pushing to $dest" >&2; exit 1; }
@@ -95,5 +106,6 @@ gitsvn doc-head.git github
 gitsvn ports-head.git github
 
 svn2git $RULES_DIR/freebsd.rules ${SRC_REPO} github
+svn2git $RULES_DIR/freebsd-base.rules ${SRC_REPO} #github
 svn2git $RULES_DIR/freebsd-doc.rules ${DOC_REPO} github
 svn2git $RULES_DIR/freebsd-ports.rules ${PORTS_REPO} github
