Fix pushing after refactoring in r352632

diff --git a/git_conv b/git_conv
--- a/git_conv
+++ b/git_conv
@@ -195,7 +195,7 @@ svn2git()
 
     echo "Pushing $target to $dest"
     for d in $dest; do
-	git push $d || { echo "Error in pushing to $dest" >&2; exit 1; }
+	{ cd $target && git push $d; } || { echo "Error in pushing to $dest" >&2; exit 1; }
     done
 }
 
